### ISSUE TITLE
1.15.2

### ISSUE THREAD

**Issue by Ra1NuX** [Icosider/GlibysVoiceChat#12]
Could be possible to get a snapshot about this mod in minecraft 1.15.2? , i need it for a ROLPLAY server that i want to create.

**Comment by jdudetv** [comment]
you and everyone else my man. been radio silence since May 13th.

**Comment by wanou067** [comment]
This mod is discontinued

**Comment by jdudetv** [comment]
No it's still being worked on. 
![Screenshot_20200627-100756](https://user-images.githubusercontent.com/51935420/85909615-30008b00-b85e-11ea-8a1c-6f6ba7b7fbaf.png)

**Comment by Ivasik78** [comment]
> This mod is discontinued

Don't mislead! The mod is ready on 86% and is currently under closed testing!

**Comment by Ivasik78** [comment]
> Could be possible to get a snapshot about this mod in minecraft 1.15.2? , i need it for a ROLPLAY server that i want to create.

If you are willing to pay, I will speed up development, otherwise wait. I cannot say exactly when the update will be released, but it will be almost for all new versions starting from 1.13. I had difficulties in port the mod to new versions and now we are testing the mod to avoid past and future bugs!

**Comment by jdudetv** [comment]
> but it will be almost for all new versions starting from 1.13.

does that include 1.16.1 understand with how new it is that probably not.

**Comment by Metroite** [comment]
this didn't age well

**Comment by Romaindu35** [comment]
Will this happen soon?

**Comment by dig** [comment]
Where is the port for 1.15+? any chance that can be made public so we can help contribute?
