### ISSUE TITLE
[1.12.2] Very hard lag spikes

### ISSUE THREAD

**Issue by NikeSchuh** [Icosider/GlibysVoiceChat#19]
System Specs:
- I9 9900k
- 32GB 3600mhz Ram
- RTX 3090 ROG STRIX
Forge: 14.23.5.2854
Mod Version: 1.2.0

When entering a Server / Singeplayer world my game stutters very hard every few seconds.
I dont have any other mod installed without the mod it is working fine.

**Comment by Icosider** [comment]
So, i have a i9-10900k, 64 gb 4133 mhz ram and rtx 3090, but i don't have a lags. Are you sure you're lagging? Can I have a video demo?

**Comment by NikeSchuh** [comment]
Those lags only happen with the Gilbys Voice Chat mod if I remove the mod the lags are gone.
I can okay any other mods fine.
https://youtu.be/dVyY0vdB6WA

**Comment by Icosider** [comment]
Oh, it's really strange. I will understand this issue.

**Comment by NikeSchuh** [comment]
![unknown](https://user-images.githubusercontent.com/47360415/109153553-5bc96d00-776d-11eb-87e4-5dafa77d1d9b.png)
I also have the console output if it helps.
