### ISSUE TITLE
[1.12.2] Players Are Re-added To The Muted List Shortly After Removal

### ISSUE THREAD

**Issue by Zundrel** [Icosider/GlibysVoiceChat#4]
Players which are removed from the muted list (after being added) show back up on the list shortly afterwards. This prevents players from un-muting players at all.

I assumed at first this was an issue with stuff syncing between client and server, but through my short look it looks like all of the muting logic is handled on the client, so I'm not certain what is causing this just yet.

**Comment by Ivasik78** [comment]
Look a ClientEventHandler#entityJoinWorld, maybe here bug. I can't say for sure, as the mod only ported.
